#!/bin/bash
PERL_SCRIPT=/usr/bin/fastcgi-wrapper.pl
RETVAL=0
case "$1" in
    start)
      $PERL_SCRIPT
      RETVAL=$?
  ;;
    stop)
      killall -9 /usr/bin/perl
      RETVAL=$?
  ;;
    restart)
      killall -9 /usr/bin/perl
      $PERL_SCRIPT
      RETVAL=$?
  ;;
    *)
      echo "Usage: perl-fastcgi {start|stop|restart}"
      exit 1
  ;;
esac
exit $RETVAL
