#!/bin/sh
### BEGIN INIT INFO
# Provides:          perl-fcgi
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the perl-fcgi
# Description:       starts perl-fcgi using start-stop-daemon
### END INIT INFO
PERL_SCRIPT=/usr/bin/fastcgi-wrapper.pl
RETVAL=0
case "$1" in
    start)
      $PERL_SCRIPT >/var/log/perl-fcgi.log 2>&1
      RETVAL=$?
  ;;
    stop)
      killall -9 /usr/bin/perl
      RETVAL=$?
  ;;
    restart)
      $0 stop
      $0 start
      RETVAL=$?
  ;;
    *)
      echo "Usage: perl-fastcgi {start|stop|restart}"
      exit 1
  ;;
esac
exit $RETVAL
